encoding: utf-8

# SEO相关信息
title: Zhangwenniu Blog
description: Zhangwenniu 的个人博客
keywords: 3D Reconstruction,Blog,Pytorch,DL,Python
author: Zhangwenniu
footerText: 'Copyright © 2022 皖ICP备16016174号'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://zhangwenniu.github.io'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://blog.csdn.net/ProfSnail

# Gitalk评论系统配置
# 注意：为了安全起见，请不要在此处填写真实的clientID和clientSecret
# 请在本地开发环境中使用环境变量或其他安全方式存储这些敏感信息
gitalk:
  enable: false  # 暂时禁用Gitalk，以确保构建成功
  clientID: ''   # 留空
  clientSecret: ''  # 留空
  repo: 'zhangwenniu.github.io'
  owner: 'zhangwenniu'
  admin: ['zhangwenniu']

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: true

# 友情链接
links:
  - title: ProfSnail
    url: https://blog.csdn.net/ProfSnail
  - title: Zhangwenniu Github
    url: http://github.com/zhangwenniu


# Google Analytics
google_analytics: G-MMEQP2Q2W1